-- Remover tabelas e constraints se já existirem
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE tbl_usuarios CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SEMAFORO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE FLUXO_TRAFEGO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONDICOES_CLIMATICAS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Remover sequências se já existirem
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIOS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SEMAFORO';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FLUXO_TRAFEGO';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONDICOES_CLIMATICAS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

-- Criação da sequência para a tabela `tbl_usuarios`
CREATE SEQUENCE SEQ_USUARIOS START WITH 1 INCREMENT BY 1;

-- Criação da tabela `tbl_usuarios`
CREATE TABLE tbl_usuarios (
    usuario_id NUMBER PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    senha VARCHAR2(255) NOT NULL,
    dt_criacao DATE DEFAULT SYSDATE NOT NULL,
    role VARCHAR2(20) NOT NULL CHECK (role IN ('ADMIN', 'USER'))
);

-- Criação da sequência para a tabela `SEMAFORO`
CREATE SEQUENCE SEQ_SEMAFORO START WITH 1 INCREMENT BY 1;

-- Criação da tabela `SEMAFORO`
CREATE TABLE SEMAFORO (
    id_semaforo NUMBER PRIMARY KEY,
    localizacao VARCHAR2(100) NOT NULL,
    status_atual VARCHAR2(20) NOT NULL,
    ultima_atualizacao DATE NOT NULL
);

-- Criação da sequência para a tabela `FLUXO_TRAFEGO`
CREATE SEQUENCE SEQ_FLUXO_TRAFEGO START WITH 1 INCREMENT BY 1;

-- Criação da tabela `FLUXO_TRAFEGO`
CREATE TABLE FLUXO_TRAFEGO (
    id_fluxo NUMBER PRIMARY KEY,
    id_semaforo NUMBER NOT NULL,
    contagem_veiculos NUMBER NOT NULL CHECK (contagem_veiculos >= 0),
    horario_registro DATE NOT NULL,
    CONSTRAINT fk_fluxo_semaforo FOREIGN KEY (id_semaforo) REFERENCES SEMAFORO(id_semaforo) ON DELETE CASCADE
);

-- Criação da sequência para a tabela `CONDICOES_CLIMATICAS`
CREATE SEQUENCE SEQ_CONDICOES_CLIMATICAS START WITH 1 INCREMENT BY 1;

-- Criação da tabela `CONDICOES_CLIMATICAS`
CREATE TABLE CONDICOES_CLIMATICAS (
    id_condicao NUMBER PRIMARY KEY,
    tipo_condicao VARCHAR2(50) NOT NULL,
    intensidade VARCHAR2(50),
    horario_registro DATE NOT NULL
);
