name: workflow-fiap
on:
  push:
jobs:
  job1-tests:
    name: Rodar testes com Maven
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Rodar testes com Maven
        run: mvn test

  job2-deploy:
    name: Deploy para Azure Web App (Código)
    runs-on: ubuntu-latest
    needs: job1-tests

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Deploy do código para Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fiap-calorias'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'

  job2-goodbye:
    name: Mensagem final
    runs-on: ubuntu-latest
    needs: job1-tests

    steps:
      - name: Step - Imprimir mensagem
        run: echo "Workflow concluído com sucesso!"